headersOrigin = "config"
redirectsOrigin = "config"

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-gatsby"

[plugins.inputs]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"

[plugins.inputs]

[build]
publish = "/mnt/persist/workspace/public"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_ENV = "production"
NODE_VERSION = "22"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
cache-control = "public, max-age=0, must-revalidate"
x-xss-protection = "1; mode=block"
x-content-type-options = "nosniff"
referrer-policy = "same-origin"
x-frame-options = "DENY"

[[headers]]
for = "/static/*"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/framework-698f815cd9bee4f4b10f.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/framework-698f815cd9bee4f4b10f.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/framework-698f815cd9bee4f4b10f.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-index-js-3689d969e7e67acd256d.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-index-js-3689d969e7e67acd256d.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-index-js-3689d969e7e67acd256d.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/108-a6f6f5e493b728c0d61a.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/108-a6f6f5e493b728c0d61a.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/108-a6f6f5e493b728c0d61a.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/app-35df1893b4eea86fdcb8.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/app-35df1893b4eea86fdcb8.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/app-35df1893b4eea86fdcb8.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/styles.9ede0f2de6743ecf1fae.css/"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/c0b03ecfeac71231e378ab5f4a87460e1424d7c4-f5b7e89f74b2423f353c.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/c0b03ecfeac71231e378ab5f4a87460e1424d7c4-f5b7e89f74b2423f353c.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-404-js-e83b57a5dba368ac763f.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-404-js-e83b57a5dba368ac763f.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-using-typescript-tsx-0b8fa6552703522620c6.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-using-typescript-tsx-0b8fa6552703522620c6.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/webpack-runtime-04dbbae53b5b9e26a4de.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/webpack-runtime-04dbbae53b5b9e26a4de.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/2cca2479-7143c6b2499609fc18bd.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/2cca2479-7143c6b2499609fc18bd.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/2cca2479-7143c6b2499609fc18bd.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-blog-index-js-a815a1cf576c2239af1e.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-blog-index-js-a815a1cf576c2239af1e.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/452-1633a306485818182bd0.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/452-1633a306485818182bd0.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/admin/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"

[[redirects]]
from = "/admin"
to = "/admin/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]