[build]
  publish = "public"
  command = "rm -rf node_modules package-lock.json .cache && npm install --legacy-peer-deps --force && npm run build && cp -r static/admin public/"

[build.environment]
  NODE_VERSION = "18"
  GATSBY_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = ["!admin/*"]}
