
# 🧠 CONFIGURACIÓN NETLIFY - PSICOLOGÍA PROFESIONAL
# Optimizada para máximo rendimiento y seguridad

[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  NETLIFY_CLI_VERSION = "latest"
  NODE_VERSION = "18"

# Configuración del CMS
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Headers de seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Cache-Control = "no-cache"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects optimizados
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/wp-admin/*"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/wordpress/*"
  to = "/"
  status = 301

# Formularios de contacto
[[redirects]]
  from = "/contacto"
  to = "/"
  status = 200
  force = false

# SPA fallback para el admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# 404 personalizada
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
